apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: front-app
spec:
  replicas: 2
  selector:
    matchLabels:
      service: webapp
  template:
    metadata:
      labels:
        app: front-app
        service: webapp
    spec:
      containers:
        - name: front-web
          image: angular-k8s:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Never         
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5	  	                                                   
---
apiVersion: v1
kind: Service
metadata:
  name: webappservice
  labels:
    app: front-app
    service: webapp
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort : 80
      protocol: TCP
  selector:
    service: webapp
